DROP TABLE SYS_USER;
CREATE TABLE SYS_USER(
	USERID 				NUMBER(11) NOT NULL,
	USERNAME 			VARCHAR2(50),
	PASSWORD			VARCHAR2(50),
	FULLNAME			VARCHAR2(50),
	SEX					NUMBER(6),
	PHONE				VARCHAR2(50),
	EMAIL				VARCHAR2(50),
	ACTIVEFLAG			NUMBER(6),
	CREATEDATE			VARCHAR2(14)
);

ALTER TABLE SYS_USER ADD PRIMARY KEY (USERID);

INSERT  INTO SYS_USER(USERID,USERNAME,PASSWORD,FULLNAME,SEX,PHONE,EMAIL,ACTIVEFLAG,CREATEDATE) VALUES (1,'admin','96E79218965EB72C92A549DD5A330112','超级管理员',1,'','',1,TO_CHAR( SYSDATE,'YYYYMMddHHmmss'));

CREATE TABLE SYS_MENU(
	MENUID 			NUMBER(11) NOT NULL,
	MENUNO 			VARCHAR2(10),
	MENUPARENTNO 	VARCHAR2(10),
	MENUORDER		NUMBER(11),
	MENUNAME	 	VARCHAR2(50),
	MENUURL			VARCHAR2(100),
	ISVISIBLE		NUMBER(6)
);
ALTER TABLE SYS_MENU ADD PRIMARY KEY (MENUID);

INSERT  INTO SYS_MENU(MENUID,MENUNO,MENUPARENTNO,MENUORDER,MENUNAME,MENUURL,ISVISIBLE) VALUES (1,'M0001','M0000',1,'系统管理','',1);
INSERT  INTO SYS_MENU(MENUID,MENUNO,MENUPARENTNO,MENUORDER,MENUNAME,MENUURL,ISVISIBLE) VALUES (2,'M0002','M0001',1,'用户管理','/system/user.action',1);
INSERT  INTO SYS_MENU(MENUID,MENUNO,MENUPARENTNO,MENUORDER,MENUNAME,MENUURL,ISVISIBLE) VALUES (3,'M0003','M0002',2,'角色管理','/system/role.action',1);